### ISSUE TITLE
Find OSX and Debian compatible solution to formatting ROBOT output to Markdown

### ISSUE THREAD

**Issue by grosscol** [Display-Lab/psdo#141]
Currently, GNU sed would work for the solution, but FreeBSD sed will not interpret \n sequences in the substitution string.  This means that the substitution string has to literally escape newlines.  Additionally, there is an issue with carriage returns appearing in the output.

Prefer using a suite of tools that currently come standard with OSX.
Alternatively, could require awk as it's installable on OSX.
Finally, could require a runtime such as python or ruby.

**Comment by CooperStansbury** [comment]
@grosscol May be trivial - thoughts on adding a python dependency here instead of Robot to build the dictionary?

**Comment by grosscol** [comment]
@CooperStansbury sounds good to me.  The reason for finding a stock Debian and OSX solution was to lower the bar to contributing and working with the repo.  Python is installed on most systems or is sufficiently easy to get.

If you're depending on installing other packages in to leverage, then the complexity for entry and maintenance increases.  It's just a cost to be aware of, but I have no objections.

Include instructions in the contributing section if running it is required for acceptable contributions.

**Comment by CooperStansbury** [comment]
@grosscol for maintenance reasons alone I am inclined to develop tools like this separately, and not require them for a development process. 

This works for now
