### ISSUE TITLE
Need derivations of is_about for performers, ISRs, and templates

### ISSUE THREAD

**Issue by grosscol** [Display-Lab/psdo#153]
The spek is about performers, ISRs, and templates.  IAO predicate `is about` (http://purl.obolibrary.org/obo/IAO_0000136) seems fit for purpose.  However, we should have child properties in order to keep the three separate.  Each property should have a range specified to one of the three types.  Essentially:

- `is about performers`
- `is about isrs`
- `is_about_templates`

This avoids having a single bag of `is about` with a mix of the three types as objects.

**Comment by CooperStansbury** [comment]
Will discuss with Zach tomorrow. 

Thanks,

**Comment by CooperStansbury** [comment]
5b96e79

```
    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/slowmo#slowmo_0000001">
        <rdfs:label>is_about_performers</rdfs:label>
    </owl:ObjectProperty>


    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/slowmo#slowmo_0000002">
        <rdfs:label>is_about_ISRs</rdfs:label>
    </owl:ObjectProperty>

    <!-- http://purl.obolibrary.org/obo/slowmo#slowmo_0000003 -->

    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/slowmo#slowmo_0000003">
        <rdfs:label xml:lang="en">is_about_templates</rdfs:label>
    </owl:ObjectProperty>
```

**Comment by CooperStansbury** [comment]
the commit above was made in slowmo.
