### ISSUE TITLE
replace term 'dimension' with 'set' for RIDs' represented dimensions

### ISSUE THREAD

**Issue by zachll** [Display-Lab/psdo#161]
e.g. ascribee dimension -> ascribee set

**Comment by CooperStansbury** [comment]
@zachll will not replace blindly. For example, some uses of the word 'dimension' refer explicitly to Zhang, and these will remain 'dimension.' 

Plan to update and submit a PR tomorrow sometime.

**Comment by grosscol** [comment]
Closed by #162
