### ISSUE TITLE
update PURLs: need to capitalize to meet OBO Foundry requirements

### ISSUE THREAD

**Issue by CooperStansbury** [Display-Lab/psdo#186]
Term purls need to be capitalized to fulfill https://github.com/OBOFoundry/OBOFoundry.github.io/issues/737 and have resolution in OBO Foundry. 

This may impact machinery outside of the ontology. 

If there are other non-trivial items, I'd ask @zachll to take a look.

**Comment by CooperStansbury** [comment]
see https://github.com/Display-Lab/psdo/pull/187

**Comment by grosscol** [comment]
I don't think this will immediately impact the pipeline.  The IRIs that are used by each of the projects are defined in their package constants.  Both bitstomach and pictoralist depend on spekex for the IRIs, so that make updating them easier as it can be done in one place.

**Comment by zachll** [comment]
The changes all looked good and I've merged the PR
